version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend-code:/usr/share/nginx/html
    networks:
      - frontend-backend-network
    environment:
      - NGINX_HOST=frontend.example.com
      - NGINX_PORT=80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - backend-code:/app
    networks:
      - frontend-backend-network
    

networks:
  frontend-backend-network:
    driver: bridge

volumes:
  frontend-code:
  backend-code: